version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "polly-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9t3u6091h3zh"
s3_prefix = "polly-api"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
